package com.vn.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShoeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeAllPropertiesEquals(Shoe expected, Shoe actual) {
        assertShoeAutoGeneratedPropertiesEquals(expected, actual);
        assertShoeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeAllUpdatablePropertiesEquals(Shoe expected, Shoe actual) {
        assertShoeUpdatableFieldsEquals(expected, actual);
        assertShoeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeAutoGeneratedPropertiesEquals(Shoe expected, Shoe actual) {
        assertThat(actual)
            .as("Verify Shoe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeUpdatableFieldsEquals(Shoe expected, Shoe actual) {
        assertThat(actual)
            .as("Verify Shoe relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDecription()).as("check decription").isEqualTo(expected.getDecription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeUpdatableRelationshipsEquals(Shoe expected, Shoe actual) {
        assertThat(actual)
            .as("Verify Shoe relationships")
            .satisfies(a -> assertThat(a.getBrand()).as("check brand").isEqualTo(expected.getBrand()));
    }
}
