package com.vn.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShoeVariantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeVariantAllPropertiesEquals(ShoeVariant expected, ShoeVariant actual) {
        assertShoeVariantAutoGeneratedPropertiesEquals(expected, actual);
        assertShoeVariantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeVariantAllUpdatablePropertiesEquals(ShoeVariant expected, ShoeVariant actual) {
        assertShoeVariantUpdatableFieldsEquals(expected, actual);
        assertShoeVariantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeVariantAutoGeneratedPropertiesEquals(ShoeVariant expected, ShoeVariant actual) {
        assertThat(actual)
            .as("Verify ShoeVariant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeVariantUpdatableFieldsEquals(ShoeVariant expected, ShoeVariant actual) {
        assertThat(actual)
            .as("Verify ShoeVariant relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDecription()).as("check decription").isEqualTo(expected.getDecription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoeVariantUpdatableRelationshipsEquals(ShoeVariant expected, ShoeVariant actual) {
        assertThat(actual)
            .as("Verify ShoeVariant relationships")
            .satisfies(a -> assertThat(a.getShoe()).as("check shoe").isEqualTo(expected.getShoe()));
    }
}
