# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: postgres
    password: admin123

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDRmOTU2NmI2YTA1ZWQyNzM2NDZjZGYyZjgzMzM1ZWVlN2M1ZjAxYTYwMzE4NjY4OWQ3MDhlYmE1YTA0YTY0Y2FkZDdjNmZiMjRlYjVhNTM0M2JjY2EyN2VkNWQ4NTBjZDU4MWZjOTE0OTYwZTdhODRkY2Y4ODM5MTI4YjNhYzQ=
