const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.resolve(__dirname, '..');
const SRC_I18N = path.join(ROOT, 'src', 'i18n');
const OUT_DIR = path.join(ROOT, 'public', 'i18n');
const HASH_OUT = path.join(ROOT, 'src', 'app', 'config', 'i18n-hash.generated.ts');

const deepMerge = (target, source) => {
  for (const [key, value] of Object.entries(source)) {
    if (Array.isArray(value)) {
      target[key] = value.slice();
      continue;
    }

    if (value && typeof value === 'object') {
      const existing = target[key];
      target[key] = deepMerge(existing && typeof existing === 'object' && !Array.isArray(existing) ? existing : {}, value);
      continue;
    }

    target[key] = value;
  }

  return target;
};

if (!fs.existsSync(SRC_I18N)) {
  console.warn('merge-i18n: src/i18n not found, skipping.');
  process.exit(0);
}

const languageDirs = fs
  .readdirSync(SRC_I18N, { withFileTypes: true })
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name)
  .sort();

if (languageDirs.length === 0) {
  console.warn('merge-i18n: no language directories found, skipping.');
  process.exit(0);
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const hashParts = [];

for (const language of languageDirs) {
  const languageDir = path.join(SRC_I18N, language);
  const files = fs.readdirSync(languageDir).filter(file => file.endsWith('.json')).sort();
  const merged = {};

  for (const file of files) {
    const filePath = path.join(languageDir, file);
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    deepMerge(merged, parsed);
  }

  const content = `${JSON.stringify(merged, null, 2)}\n`;
  const outFile = path.join(OUT_DIR, `${language}.json`);
  fs.writeFileSync(outFile, content, 'utf8');
  hashParts.push(content);
  console.log(`merge-i18n: ${language} -> ${path.relative(ROOT, outFile)} (${files.length} files)`);
}

const hash = crypto.createHash('md5').update(hashParts.join('')).digest('hex').slice(0, 12);
const hashContent =
  `/** Generated by scripts/merge-i18n.cjs - do not edit */\n` + `export const I18N_HASH = '${hash}';\n`;
fs.writeFileSync(HASH_OUT, hashContent, 'utf8');
console.log(`merge-i18n: I18N_HASH -> ${path.relative(ROOT, HASH_OUT)}`);
