import { AppNavigationLeaf, AppNavigationSection } from './navigation.model';

export const APP_NAVIGATION_TREE: readonly AppNavigationSection[] = [
  {
    id: 'home',
    sectionId: 'home',
    labelKey: 'global.menu.home',
    icon: 'pi pi-home',
    routerLink: ['/'],
    routePrefix: '/',
    breadcrumbKey: 'global.menu.home',
    deniedMode: 'route',
    children: [
      {
        id: 'home.dashboard',
        sectionId: 'home',
        labelKey: 'global.menu.home',
        icon: 'pi pi-home',
        routerLink: ['/'],
        routePrefix: '/',
        breadcrumbKey: 'global.menu.home',
        deniedMode: 'route',
      },
    ],
  },
  {
    id: 'entities',
    sectionId: 'entities',
    labelKey: 'global.menu.entities.main',
    icon: 'pi pi-building',
    routerLink: ['/entities/organization'],
    routePrefix: '/entities',
    breadcrumbKey: 'global.menu.entities.main',
    deniedMode: 'route',
    children: [
      {
        id: 'entities.brand',
        sectionId: 'entities',
        labelKey: 'global.menu.entities.brand',
        icon: 'pi pi-tag',
        routerLink: ['/entities/brand'],
        routePrefix: '/entities/brand',
        breadcrumbKey: 'global.menu.entities.brand',
        deniedMode: 'in-shell',
      },
      {
        id: 'entities.shoe',
        sectionId: 'entities',
        labelKey: 'global.menu.entities.shoe',
        icon: 'pi pi-box',
        routerLink: ['/entities/shoe'],
        routePrefix: '/entities/shoe',
        breadcrumbKey: 'global.menu.entities.shoe',
        deniedMode: 'in-shell',
      },
      {
        id: 'entities.shoe-variant',
        sectionId: 'entities',
        labelKey: 'global.menu.entities.shoeVariant',
        icon: 'pi pi-clone',
        routerLink: ['/entities/shoe-variant'],
        routePrefix: '/entities/shoe-variant',
        breadcrumbKey: 'global.menu.entities.shoeVariant',
        deniedMode: 'in-shell',
      },
      {
        id: 'entities.organization',
        sectionId: 'entities',
        labelKey: 'global.menu.entities.organization',
        icon: 'pi pi-building',
        routerLink: ['/entities/organization'],
        routePrefix: '/entities/organization',
        breadcrumbKey: 'global.menu.entities.organization',
        deniedMode: 'in-shell',
      },
      {
        id: 'entities.department',
        sectionId: 'entities',
        labelKey: 'global.menu.entities.department',
        icon: 'pi pi-sitemap',
        routerLink: ['/entities/department'],
        routePrefix: '/entities/department',
        breadcrumbKey: 'global.menu.entities.department',
        deniedMode: 'in-shell',
      },
      {
        id: 'entities.employee',
        sectionId: 'entities',
        labelKey: 'layout.menu.entities.employee',
        icon: 'pi pi-users',
        routerLink: ['/entities/employee'],
        routePrefix: '/entities/employee',
        breadcrumbKey: 'layout.menu.entities.employee',
        deniedMode: 'in-shell',
      },
    ],
  },
  {
    id: 'security',
    sectionId: 'security',
    labelKey: 'layout.menu.security.main',
    icon: 'pi pi-shield',
    routerLink: ['/admin/users'],
    routePrefix: '/admin',
    breadcrumbKey: 'layout.menu.security.main',
    deniedMode: 'route',
    children: [
      {
        id: 'security.users',
        sectionId: 'security',
        labelKey: 'global.menu.admin.userManagement',
        icon: 'pi pi-users',
        routerLink: ['/admin/users'],
        routePrefix: '/admin/users',
        breadcrumbKey: 'global.menu.admin.userManagement',
        deniedMode: 'route',
      },
      {
        id: 'security.roles',
        sectionId: 'security',
        labelKey: 'layout.menu.security.roles',
        icon: 'pi pi-shield',
        routerLink: ['/admin/security/roles'],
        routePrefix: '/admin/security/roles',
        breadcrumbKey: 'layout.menu.security.roles',
        deniedMode: 'route',
      },
      {
        id: 'security.menu-definitions',
        sectionId: 'security',
        labelKey: 'layout.menu.security.menuDefinitions',
        icon: 'pi pi-list',
        routerLink: ['/admin/security/menu-definitions'],
        routePrefix: '/admin/security/menu-definitions',
        breadcrumbKey: 'layout.menu.security.menuDefinitions',
        deniedMode: 'route',
      },
    ],
  },
];

export const APP_NAVIGATION_LEAVES: readonly AppNavigationLeaf[] = APP_NAVIGATION_TREE.flatMap(section => section.children);
